### PR TITLE
Add Charident

### PR DESCRIPTION
**Pull request by mcdurdin**
Adding via git as it's not big enough to transfer via other means.

### CODE REVIEW

**Review by darcywong00 — COMMENTED** [review]
Does an .htaccess file need to be modified to access this new tools/ folder?

**Comment by darcywong00** [comment]
And does readme.md get updated about the charident.exe  file getting synced?

**Comment by mcdurdin** [comment]
@darcywong00 stop asking me difficult questions ;-)

**Comment by mcdurdin** [comment]
.htaccess shouldn't be required

**Comment by mcdurdin** [comment]
Okay, should be ready for review again...

**Review by darcywong00 — APPROVED** [review]
lgtm

**Pull request merged**
